name: Fifteenth Workflow
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Math expression
        run: expr 2 + 2 > math-result.txt
      - name: Upload result file
        uses: actions/upload-artifact@v4.3.1
        with:
          name: math-result
          path: math-result.txt
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download file
        uses: actions/download-artifact@v4.1.4
        with:
          name: math-result
      - name: Print file
        run: |
          value=`cat math-result.txt`
          echo $value