name: Fourth Workflow
on:
  workflow_run:
   workflows: [Third Workflow]
   types:
    - completed

jobs:
  hello-command:
    runs-on: ubuntu-latest
    steps:
      - name: Text Output
        run: echo "Hello, $GITHUB_ACTOR!"