name: Sixteenth Workflow
on: push

jobs:
  testing-matrix-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
