name: Thirteenth Workflow
on: push

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: leep 30
      - name: Runs on Cancelled
        if: ${{ cancelled() }}
        run: echo "Runs on Cancelled"
      - name: Runs on any case
        if: ${{ always() }}
        run: echo "Runs on any case"
      - name: Runs on Success
        if: ${{ success() }}
        run: echo "Runs on Success"
      - name: Runs on Failure
        if: ${{ failure() }}
        run: echo "Runs on Failure"