name: Test Timeout
on: push

jobs:
  test-timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1 # Таймаут на уровне джоба
    steps:
      - name: Some Step
        run: sleep 200
        timeout-minutes: 1 # Таймаут на уровне шага