name: Twelfth Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    environment: "production"
    steps:
      - name: Our Vars & Secrets
        run: |
          echo "${{ vars.STATUS }}"
          echo "${{ secrets.PASSWORD }}"